/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FaqEntry {
  'question' : string,
  'lastUpdated' : bigint,
  'answer' : string,
  'isActive' : boolean,
}
export interface PricingDetail {
  'lastUpdated' : bigint,
  'description' : string,
  'isActive' : boolean,
  'price' : string,
}
export interface TeamMember {
  'bio' : string,
  'name' : string,
  'photoUrl' : string,
  'position' : string,
}
export interface _SERVICE {
  'addFaqEntry' : ActorMethod<[string, string], undefined>,
  'addTeamMember' : ActorMethod<[string, string, string, string], undefined>,
  'getAllActiveFaqEntries' : ActorMethod<[], Array<FaqEntry>>,
  'getPricingDetails' : ActorMethod<[], [] | [PricingDetail]>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'registerUser' : ActorMethod<[string, string, string, boolean], undefined>,
  'setPricingDetails' : ActorMethod<[string, string], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'updateFaqEntry' : ActorMethod<[string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];