/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FaqEntry = IDL.Record({
  'question' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'answer' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const PricingDetail = IDL.Record({
  'lastUpdated' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'position' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFaqEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTeamMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllActiveFaqEntries' : IDL.Func([], [IDL.Vec(FaqEntry)], ['query']),
  'getPricingDetails' : IDL.Func([], [IDL.Opt(PricingDetail)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'setPricingDetails' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateFaqEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FaqEntry = IDL.Record({
    'question' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'answer' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const PricingDetail = IDL.Record({
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'position' : IDL.Text,
  });
  
  return IDL.Service({
    'addFaqEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllActiveFaqEntries' : IDL.Func([], [IDL.Vec(FaqEntry)], ['query']),
    'getPricingDetails' : IDL.Func([], [IDL.Opt(PricingDetail)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
    'setPricingDetails' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateFaqEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };